name: ci

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: [lts/*, current]
    env:
      CI: true
    steps:
      - name: Checkout ${{ github.sha }}
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint --if-present
      - name: Build
        run: npm run build --if-present
      - name: Test
        run: npm run test --if-present
      - name: Publish coverage
        if: matrix.node-version == 'current'
        uses: coverallsapp/github-action@v2
        with:
          format: clover
          file: packages/timeago-react/coverage/clover.xml
          github-token: ${{ secrets.GITHUB_TOKEN }}
