name: build 

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [lts/*, current]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and test
      run: |
        npm install
        npm run ci
      env:
        CI: true
    - name: coverall
      if: success()
      uses: coverallsapp/github-action@v2
      with:
        format: clover
        file: coverage/clover.xml
        github-token: ${{ secrets.GITHUB_TOKEN }}
